// <auto-generated />
using FinalProjectRyan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectRyan.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20230429173345_CreateGamingStore")]
    partial class CreateGamingStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectRyan.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Laptops"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Desktops"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Monitors"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Keyboards"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Headsets"
                        });
                });

            modelBuilder.Entity("FinalProjectRyan.Models.Products", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            ProductBrand = "ASUS",
                            ProductModel = "TUF DASH F15",
                            ProductPrice = 1299.99
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            ProductBrand = "Corsair",
                            ProductModel = "VENGEANCE i7200 Gaming PC",
                            ProductPrice = 1999.99
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 3,
                            ProductBrand = "Samsung",
                            ProductModel = "27in Odyssey G32A FHD 1ms 165Hz Gaming Monitor w/ Free Sync",
                            ProductPrice = 189.99000000000001
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 4,
                            ProductBrand = "Logitech",
                            ProductModel = "G Pro Mechanical Gaming Keyboard",
                            ProductPrice = 90.989999999999995
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 5,
                            ProductBrand = "Logitech",
                            ProductModel = "G733 Lightspeed Wireless Gaming Headset w/ Suspension Headband, Lightsync RGB, Blue Voice Mic Technology - Black",
                            ProductPrice = 133.99000000000001
                        });
                });

            modelBuilder.Entity("FinalProjectRyan.Models.Products", b =>
                {
                    b.HasOne("FinalProjectRyan.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
